In [2]:
%pip install geopandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.13.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 14.1 MB/s eta 0:00:00
Collecting fiona>=1.8.19 (from geopandas)
  Downloading Fiona-1.9.4.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 66.5 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (23.1)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.5.3)
Collecting pyproj>=3.0.1 (from geopandas)
  Downloading pyproj-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 86.0 MB/s eta 0:00:00
Requirement already satisfied: shapely>=1.7.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (2022.12.7)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (8.1.3)
Collecting click-plugins>=1.0 (from fiona>=1.8.19->geopandas)
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting cligj>=0.5 (from fiona>=1.8.19->geopandas)
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (1.22.4)
Installing collected packages: pyproj, cligj, click-plugins, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.4.post1 geopandas-0.13.2 pyproj-3.5.0

In [3]:
#Passer d'un fichier GEOJSON à un fichier CSV sans perdre les données géographiques
import geopandas as gpd
import io 
import pandas as pd

url = "/content/ter_territoire.terpopulation_latest.geojson"

population = gpd.read_file(url)
population_df = pd.DataFrame(population)
population_df.to_csv('population.csv', index=True)

In [ ]:
#Récupérer les informations pour chaque colonne du tableau (nombre de colonnes avec des lignes nulles notamment)
population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4128 entries, 0 to 4127
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   nom                     4128 non-null   object
 1   commune1                4128 non-null   object
 2   insee1                  4128 non-null   object
 3   commune2                4128 non-null   object
 4   insee2                  4128 non-null   object
 5   reseau                  4128 non-null   object
 6   financementac           4128 non-null   object
 7   typeamenagement         4128 non-null   object
 8   typeamenagement2        4128 non-null   object
 9   positionnement          4128 non-null   object
 10  senscirculation         4128 non-null   object
 11  environnement           4128 non-null   object
 12  localisation            4128 non-null   object
 13  typologiepiste          4128 non-null   object
 14  revetementpiste         4128 non-null   object
 15  domanialite             4128 non-null   object
 16  reglementation          4128 non-null   object
 17  zonecirculationapaisee  4128 non-null   object
 18  anneelivraison          3566 non-null   float64
 19  longueur                4128 non-null   float64
 20  observation             4128 non-null   object
 21  gid                     4128 non-null   int64
 22  geometry                4128 non-null   geometry
dtypes: float64(2), geometry(1), int64(1), object(19)
memory usage: 741.9+ KB

In [4]:
population_df

,commune,insee,pop2019,pop2018,pop2017,pop2016,pop2015,pop2014,pop2013,pop2012,pop2011,pop2010,pop2009,pop2008,pop2007,pop2006,gid,geometry
0,Albigny-sur-Saône,69003,2989,2952,2919,2871,2875,2859,2842,2830,2791,2780,2783,2786,2778,2760,1,"POLYGON ((4.81773 45.85597, 4.81818 45.85591, ..."
1,Bron,69029,42645,42625,42020,41589,41232,39815,39296,39782,39371,39238,39380,39667,39415,39488,2,"POLYGON ((4.89092 45.73700, 4.89041 45.73622, ..."
2,Cailloux-sur-Fontaines,69033,2957,2875,2792,2725,2679,2617,2603,2586,2546,2532,2494,2440,2389,2356,3,"POLYGON ((4.86675 45.83829, 4.86684 45.83828, ..."
3,Caluire-et-Cuire,69034,43916,43469,43816,43546,42975,43157,43311,42785,42075,41840,41766,41436,41564,42020,4,"POLYGON ((4.84130 45.77944, 4.84303 45.77892, ..."
4,Champagne-au-Mont-d'Or,69040,5796,5617,5579,5654,5728,5875,5735,5366,5276,5186,5065,5022,5035,5035,5,"POLYGON ((4.79342 45.78928, 4.79356 45.78925, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,Tassin-la-Demi-Lune,69244,22637,22759,22691,22729,22188,22145,21543,21456,20292,19938,19345,18943,18595,18520,39,"POLYGON ((4.75249 45.75024, 4.75256 45.75023, ..."
63,Vaulx-en-Velin,69256,53016,51045,49928,48906,47746,45763,44653,43944,43298,41970,40898,40875,41137,40806,41,"POLYGON ((4.93157 45.74448, 4.93215 45.74432, ..."
64,Vénissieux,69259,67551,67397,66202,65822,64718,63102,62228,61791,60744,60448,59186,58178,57507,57754,42,"POLYGON ((4.88638 45.67157, 4.88639 45.67156, ..."
65,Vernaison,69260,5055,5057,5052,4927,4799,4671,4634,4571,4545,4519,4501,4428,4420,4374,43,"POLYGON ((4.80427 45.63023, 4.80725 45.62949, ..."
66,Villeurbanne,69266,153294,151727,148754,150375,150091,150075,148832,147940,146578,146729,146283,142552,139764,138596,44,"POLYGON ((4.91762 45.74846, 4.91774 45.74863, ..."

In [5]:
population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   commune   67 non-null     object
 1   insee     67 non-null     object
 2   pop2019   67 non-null     object
 3   pop2018   67 non-null     object
 4   pop2017   67 non-null     object
 5   pop2016   67 non-null     object
 6   pop2015   67 non-null     object
 7   pop2014   67 non-null     object
 8   pop2013   67 non-null     object
 9   pop2012   67 non-null     object
 10  pop2011   67 non-null     object
 11  pop2010   67 non-null     object
 12  pop2009   67 non-null     object
 13  pop2008   67 non-null     object
 14  pop2007   67 non-null     object
 15  pop2006   67 non-null     object
 16  gid       67 non-null     object
 17  geometry  67 non-null     geometry
dtypes: geometry(1), object(17)
memory usage: 9.5+ KB